List islamicEvents = [
  {
    "event": "Islamic New Year",
    "hijriDay": 1,
    "monthName": "Muharram",
    "hijriMonth": 1,
    "description": "Beginning of the Islamic year.",
  },
  {
    "event": "Ashura",
    "hijriDay": 10,
    "monthName": "Muharram",
    "hijriMonth": 1,
    "description": "Recommended fasting day, marks the salvation of Prophet Musa (Moses).",
  },
  {
    "event": "Mawlid",
    "hijriDay": 12,
    "monthName": "Rabi' al-Awwal",
    "hijriMonth": 3,
    "description": "Birth of Prophet Muhammad (PBUH).",
  },
  {
    "event": "Isra and Miraj",
    "hijriDay": 27,
    "monthName": "Rajab",
    "hijriMonth": 7,
    "description": "The Prophet's journey to Al-Aqsa Mosque and ascension to the heavens.",
  },
  {
    "event":  "Mid-Sha'ban",
    "hijriDay": 15,
    "monthName": "Sha'ban",
    "hijriMonth": 8,
    "description": "A night of increased supplication and forgiveness.",
  },
  {
    "event": "Start of Ramadan",
    "hijriDay": 1,
    "monthName": "Ramadan",
    "hijriMonth": 9,
    "description": "Start of the fasting month.",
  },
  {
    "event": "Laylat al-Qadr",
    "hijriDay": 27,
    "monthName": "Ramadan",
    "hijriMonth": 9,
    "description": "The best night of the year when the Quran was revealed.",
  },
  {
    "event": "Eid al-Fitr",
    "hijriDay": 1,
    "monthName": "Shawwal",
    "hijriMonth": 10,
    "description": "Festival at the end of Ramadan.",
  },
  {
    "event": "Day of Arafah",
    "hijriDay": 9,
    "monthName": "Dhul-Hijjah",
    "hijriMonth": 12,
    "description": "The greatest day of Hajj, fasting expiates sins of two years.",
  },
  {
    "event": "Eid al-Adha",
    "hijriDay": 10,
    "monthName": "Dhul-Hijjah",
    "hijriMonth": 12,
    "description": "Festival of Sacrifice, marking the act of Qurbani.",
  },
];
