List islamicEvents = [
  {
    "event": "رأس السنة الهجرية",
    "hijriDay": 1,
    "monthName": "محرم",
    "hijriMonth": 1,
    "description": "بداية العام الهجري.",
  },
  {
    "event": "يوم عاشوراء",
    "hijriDay": 10,
    "monthName": "محرم",
    "hijriMonth": 1,
    "description": "يوم صيام مستحب ويصادف نجاة سيدنا موسى عليه السلام.",
  },
  {
    "event": "المولد النبوي الشريف",
    "hijriDay": 12,
    "monthName": "ربيع الأول",
    "hijriMonth": 3,
    "description": "مولد النبي محمد ﷺ.",
  },
  {
    "event": "ليلة الإسراء والمعراج",
    "hijriDay": 27,
    "monthName": "رجب",
    "hijriMonth": 7,
    "description": "رحلة النبي ﷺ إلى المسجد الأقصى والمعراج إلى السماء.",
  },
  {
    "event": "النصف من شعبان",
    "hijriDay": 15,
    "monthName": "شعبان",
    "hijriMonth": 8,
    "description": "ليلة يكثر فيها الدعاء والاستغفار.",
  },
  {
    "event": "بداية رمضان",
    "hijriDay": 1,
    "monthName": "رمضان",
    "hijriMonth": 9,
    "description": "بداية شهر الصيام.",
  },
  {
    "event": "ليلة القدر",
    "hijriDay": 27,
    "monthName": "رمضان",
    "hijriMonth": 9,
    "description": "أفضل ليلة في السنة، حيث نزل القرآن الكريم.",
  },
  {
    "event": "عيد الفطر",
    "hijriDay": 1,
    "monthName": "شوال",
    "hijriMonth": 10,
    "description": "عيد الفطر بعد انتهاء رمضان.",
  },
  {
    "event": "يوم عرفة",
    "hijriDay": 9,
    "monthName": "ذو الحجة",
    "hijriMonth": 12,
    "description": "أعظم أيام الحج، صيامه يكفر سنتين.",
  },
  {
    "event": "عيد الأضحى",
    "hijriDay": 10,
    "monthName": "ذو الحجة",
    "hijriMonth": 12,
    "description": "عيد النحر والتضحية بالأضاحي.",
  },
];
