// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBb0PZjED-sNF22sQGs8Oy8NxQ43_yxI',
    appId: '1:515456705685:web:991b877c9883055b1f679c',
    messagingSenderId: '515456705685',
    projectId: 'muslim-app-9d5a2',
    authDomain: 'muslim-app-9d5a2.firebaseapp.com',
    storageBucket: 'muslim-app-9d5a2.appspot.com',
    measurementId: 'G-EELDG0TSC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWmSJtj7og08_eV-ivuAFkhpiyfLkHrU',
    appId: '1:515456705685:android:74cd9a4e77f061871f679c',
    messagingSenderId: '515456705685',
    projectId: 'muslim-app-9d5a2',
    storageBucket: 'muslim-app-9d5a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2757kaHVRZ9GxDB5wRvaxJZEArMKUY44',
    appId: '1:515456705685:ios:59626548e4ef9d611f679c',
    messagingSenderId: '515456705685',
    projectId: 'muslim-app-9d5a2',
    storageBucket: 'muslim-app-9d5a2.appspot.com',
    iosBundleId: 'com.RzRio.muslim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2757kaHVRZ9GxDB5wRvaxJZEArMKUY44',
    appId: '1:515456705685:ios:59626548e4ef9d611f679c',
    messagingSenderId: '515456705685',
    projectId: 'muslim-app-9d5a2',
    storageBucket: 'muslim-app-9d5a2.appspot.com',
    iosBundleId: 'com.RzRio.muslim',
  );
}
